heat_template_version: 2016-10-14

description: Linux Web_Server
 
parameters:

  server_id:
    type: string
    label: Server ID
    description: Server ID Number with No Leading Zeros

  server_name:
    type: string
    label: Server Name
    description: Server Name
    default:
    constraints:
      -  length: { min: 1, max: 15 }
         description: Server name must be no longer than 15 characters
      -  allowed_pattern: "[a-zA-Z]*"
         description: Server name may only contain letters
  
  AdminPassword:
    type: string
    label: Root Password
    description: root and admin password
    hidden: true
    default: Passw0rd
    constraints:
      -  length: { min: 8, max: 20 }
         description: Password must be between 8 and 20 characters
      -  allowed_pattern: "[a-zA-Z0-9]*"
         description: Password may not contain special characters

resources:

  network0:
    type: OS::Neutron::Net
    properties:
      name: network0
      admin_state_up: true
         
      
  subnet0:
    type: OS::Neutron::Subnet
    properties:
      allocation_pools:
        - start:
            str_replace:
              template: 10.serverID.0.200
              params:
                serverID: { get_param: server_id }
          end:
            str_replace:
              template: 10.serverID.0.250
              params:
                serverID: { get_param: server_id }
      cidr:
        str_replace:
          template: 10.serverID.0.0/24
          params:
            serverID: { get_param: server_id }
      gateway_ip:
        str_replace:
          template: 10.serverID.0.254
          params:
            serverID: { get_param: server_id }
      network: { get_resource: network0 }
      dns_nameservers: [10.50.255.254]
      name:
        str_replace:
          template: servername_subnet
          params:
            servername: { get_param: server_name }
        
  server-router:
    type: OS::Neutron::Router    
    properties:
      name:
        str_replace:
          template: servername_router
          params:
            servername: { get_param: server_name }
      external_gateway_info: {"network": public}
        
  server-router-interface:
    type:  OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: server-router }       
      subnet_id: { get_resource: subnet0 }
      
  host1-port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: network0 }
      fixed_ips:
        - subnet_id: { get_resource: subnet0 }
          ip_address:
            str_replace:
              template: 10.serverID.0.1
              params:
                serverID: { get_param: server_id }
      port_security_enabled: false
                     
  host1:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: servername_All_The_Things
          params:
            lastname: { get_param: server_name }
      image: Debian LXDE
      flavor: cy.medium
      networks: 
        - port: { get_resource: host1-port }
      user_data: 
        str_replace:
          template: |
            #!/bin/bash
            echo 127.0.0.1 $(hostname) >> /etc/hosts
            echo 173.230.138.130 git.cybbh.space >> /etc/host
            useradd -m -G sudo zeus
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get -y install locate dnsutils lsof aptitude ftp auditd telnet samba git zip unzip figlet hexedit tree qemu apache2 gcc tcc
            apt-get upgrade
            updatedb
            mandb
            mkdir /var/www/html/linux
            wget goo.gl/eGEfnd -O /var/www/html/linux/banner.sh
            wget goo.gl/pZN4ED -O /var/www/html/linux/check.pyc
            wget goo.gl/KwvVVC -O /var/www/html/linux/runme
            wget goo.gl/yhFrdp -O /var/www/html/linux/page.html
            wget goo.gl/5wG3gr -O /var/www/html/linux/fun.vdi
            wget goo.gl/Uggv6h -O /var/www/html/linux/mbroken.zip
            wget goo.gl/g9JJ9z -O /var/www/html/linux/mbrgood.zip
            wget goo.gl/FEAeHi -O /var/www/html/linux/NMAP_all_hosts.txt
            wget goo.gl/NVG6Gu -O /var/www/html/linux/LEMARCHAND.zip
            wget goo.gl/kyDrPg -O /var/www/html/linux/sorted.zip
            wget goo.gl/ijStVf -O /var/www/html/linux/PassCrack.zip
            wget goo.gl/BXvDqT -O /var/www/html/linux/warriors.zip
            mkdir /rootkits
            git clone https://github.com/D4NP0UL1N/0010100010.git /rootkits
            echo 0 > /proc/sys/kernel/randomize_va_space
            gcc -o /var/www/html/linux/sudo_bad /rootkits/sudo.c 2>/dev/null
            zip /var/www/html/linux/rootkits.zip /rootkits/*
            chmod +x /var/www/html/linux/*
            service apache2 start
            bash
            #User accounts
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
            useradd $user -m -U -s /bin/bash
            usermod -aG sudo $user
            echo "$user:$password" | chpasswd
            echo "zeus:$password" | chpasswd
            echo "root:$password" | chpasswd
            reboot
          params:
            $user: { get_param: server_name }
            $password: { get_param: AdminPassword }
      user_data_format: RAW
